resolved date issue and added seasonal stats for players and opponent…
RBecker262/ChiPyProject pull request #10
Opened 2017-06-03 21:31 UTC by RBecker262

Quite an involved set of changes with two focuses...
1. fix the date issue for "today" on the three master file builds (schedule, player, team)
2. added relevant seasonal stats to player
3. added opponent name and time of game info to team master

Opponent will read like "at Chicago Cubs" for the Cardinals team entry and "vs St Louis Cardinals" for the Cubs team entry. Game time is in local time based on team. Also did a kick ass job on comments and keeping functions small since I added a LOT of code.

2017-06-11 21:19 UTC, alesage requested changes
I like it, sorry for the delay in reviewing--in my defense this actually is a large review, I'd suggest (next time) doing the date changes, e.g. as a separate pull request b/c that's a no-brainer and quick to press 'yes' on.

Any thoughts on that one signature change I suggested?

2017-06-11 21:19 UTC, alesage commented on updplayer.py
> +    :param indict:  boxscore dictionary from which to extract player data
I would just extract the keys for the client e.g. using indict.keys() unless there's a reason these might differ?

2017-06-11 21:19 UTC, alesage commented on updplayer.py
> +    :param indict:  boxscore dictionary from which to extract player data
Ditto above.

2017-06-12 11:33 UTC, RBecker262 commented on updplayer.py
> +    :param indict:  boxscore dictionary from which to extract player data
Agreed, made change, tested, and pushed up here. Just looked at notes and forgot about putting the param to close an issue, will try to remember next time.

2017-06-12 11:33 UTC, RBecker262 commented on updplayer.py
> +    :param indict:  boxscore dictionary from which to extract player data
Ditto my comment above.

2017-06-12 21:40 UTC, alesage approved these changes

2017-06-12 21:40 UTC, merged